ordena: dados.c dados.h insertionSort.c insertionSort.h testeOrdena.c
	gcc -o ordena dados.c insertionSort.c testeOrdena.c
teste1: dados.c dados.h teste1.c
	gcc -o teste1 dados.c dados.h teste1.c
teste2: dados.c dados.h teste2.c
	gcc -o teste2 dados.c dados.h teste2.c
executaOrdena: ordena
	./ordena
executaTeste1: teste1
	./teste1
executaTeste2: teste2
	./teste2
	
